CREATE TABLE sensors(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  device TEXT NOT NULL,
  name TEXT NOT NULL
);

CREATE TABLE logs(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sensor_id INTEGER NOT NULL,
  temperature REAL NOT NULL,
  sensor_status INTEGER NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY(sensor_id) REFERENCES sensors(id)
);
